name: Feature request
description: A **short and sweet** title for your issue that **briefly** describes what your issue is about. If you wanna go into detail, do that below.
title: "*Coolest title ever*"
labels: Suggestion
body:
  - type: textarea
    attributes:
      label: What would you like to add?
      description: Here you can go into detail about what you want to add. Try to be specific enough so that I can tell what it is you want to change. (stop asking me to add new versions, i'll do that in my own time.)
      placeholder: Make a wizard do the dab because it's so trendy and would never be outdated ever.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How would you like this to be implemented? (optional)
      description: You can tell me how you would like me to make this if there is a preferred way.
      placeholder: Put on some sunglasses and do a dance!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional context (optional)
      description: Any other important context you may have for making this issue.
      placeholder: Accidental tiktok dance.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Type of suggestion
      description: Select which type of feature request you're submitting.
      options:
        - New Prodigy Definitive Edition feature
        - New modpack
        - Something super awesome from a fork you play
        - A new Prodigy version
        - Other
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: I agree to the following
      options:
        - label: By checking this box, I confirm that this issue is NOT about adding a new Prodigy version.
          required: true
        - label: By checking this box, I confirm that I haven't already made an issue about the topic being presented in this issue.
          required: true
